### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [paudan/pmml-weka#2]
Hello, I was wondering if you are planning to assign any open source license, like MIT, BSD or GPL to this code.

I would like forking it, make some modifications, and assign any of the licenses mentioned above, whichever you choose.

**Comment by paudan** [comment]
Hi Alberto, very glad of you to find this project interesting. I assigned GPL license (the same as used by Weka), hence, you can freely use it. 
Btw, feel free to submit pull requests if you would find those modifications relevant. I did not have enough time to continue with this project at the time I started developing it, but any improvements and features are welcome.

**Comment by AlbertoCasasOrtiz** [comment]
Thank you so much.

I managed to make the PMML producer work on Weka 3.9, but the PMML Consumer is still on the way. If I can make it work for both the producer and the consumer, I'll make a pull request to your repository.
